apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30732  # Ensure this matches the NodePort you are using
  type: NodePort
