name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Remove all old Go versions
      - name: Remove Old Go Versions
        run: |
          sudo rm -rf /usr/local/go /opt/hostedtoolcache/go

      # Step 3: Set up the required Go version
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      # Step 4: Verify the correct Go version is used
      - name: Verify Go Version
        run: |
          echo "PATH: $PATH"
          echo "GOROOT: $GOROOT"
          go version

      # Step 5: Build and test services
      - name: Build and Test Services
        run: |
          cd services/product && go mod tidy && go test ./...
          cd ../user && go mod tidy && go test ./...
          cd ../order && go mod tidy && go test ./...

  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Debug Secrets (for testing only)
      - name: Debug Secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "Docker Username: $DOCKER_USERNAME"
          echo "Access Token Length: ${#DOCKER_ACCESS_TOKEN}"

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and push Docker images
      - name: Build and Push Product Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./services/product
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and Push User Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./services/user
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and Push Order Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./services/order
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

  deploy-to-kubernetes:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Minikube and kubectl
      - name: Install Minikube and kubectl
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo chmod +x minikube
          sudo mv minikube /usr/local/bin/

          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubectl"
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/

      # Start Minikube Cluster
      - name: Start Minikube Cluster
        run: |
          minikube start --driver=docker

      # Configure kubectl to use the Minikube cluster
      - name: Set KUBECONFIG for kubectl
        run: |
          echo "$(minikube kubeconfig)" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      # Deploy services to Minikube Kubernetes Cluster
      - name: Deploy Product Service to Minikube
        run: |
          kubectl apply -f k8s/product
          kubectl get pods

      - name: Deploy User Service to Minikube
        run: |
          kubectl apply -f k8s/user
          kubectl get pods

      - name: Deploy Order Service to Minikube
        run: |
          kubectl apply -f k8s/order
          kubectl get pods

      # Optional: Clean up Minikube
      - name: Stop Minikube
        run: |
          minikube stop
