name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Remove pre-installed Go to avoid conflicts
      - name: Remove Pre-installed Go
        run: |
          sudo rm -rf /usr/local/go
          sudo rm -rf /opt/hostedtoolcache/go
          which go || echo "Go is not installed"

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Update PATH to use the new Go version
      - name: Update PATH for Go 1.20
        run: |
          echo "PATH=$(go env GOPATH)/bin:$PATH" >> $GITHUB_ENV

      # Verify Go environment
      - name: Verify Go Environment
        run: |
          echo "PATH: $PATH"
          echo "GOROOT: $GOROOT"
          echo "GOPATH: $GOPATH"
          which go
          go version
          go env

      # Install dependencies and run tests
      - name: Install Dependencies and Run Tests
        run: |
          cd services/product && go mod tidy && go test ./...
          cd ../user && go mod tidy && go test ./...
          cd ../order && go mod tidy && go test ./...

  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and push Docker images
      - name: Build and Push Product Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./services/product
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Build and Push User Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./services/user
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and Push Order Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./services/order
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.2

      # Configure Kubernetes context
      - name: Configure Kubernetes Context
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      # Deploy to Kubernetes
      - name: Deploy Product Service
        run: kubectl apply -f k8s/product

      - name: Deploy User Service
        run: kubectl apply -f k8s/user

      - name: Deploy Order Service
        run: kubectl apply -f k8s/order